[ftplugin]
denite = '''
nnoremap <silent><buffer><expr> <cr>    denite#do_map('do_action')
nnoremap <silent><buffer><expr> <tab>   denite#do_map('choose_action')
nnoremap <silent><buffer><expr> <c-l>   denite#do_map('redraw')
nnoremap <silent><buffer><expr> <esc>   denite#do_map('quit')
nnoremap <silent><buffer><expr> <space> denite#do_map('toggle_select').'j'
nnoremap <silent><buffer><expr> *       denite#do_map('toggle_select_all')
nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> u       denite#do_map('restore_sources')
nnoremap <silent><buffer><expr> -       denite#do_map('move_up_path')
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_verbose = 0
'''

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
let g:edge_enable_italic = 1
colorscheme edge
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = "lua require'plugin_settings.nvim-colorizer'"

[[plugins]]
repo = 'hardcoreplayers/spaceline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = '''
call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep', '--no-heading'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#option('_', {'auto_resize': 1, 'split': 'floating', 'prompt': 'ï„ '})
call denite#custom#source('grep', { 'args': ['', '', '!'] })
call denite#custom#source('deol', { 'args': ['-edit -split=floating'] })

noremap <silent><tab> :Denite source command<CR>
'''

[[plugins]]
repo = 'tk-shirasaka/denite-utils'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
call deoplete#enable()
call deoplete#custom#option({'ignore_case': 1, 'ignore_sources': {'_': ['around', 'file', 'member', 'omni']}})
call deoplete#custom#option('sources', {'denite-filter': ['denite']})
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_source = "lua require'plugin_settings.nvim-lspconfig'"

[[plugins]]
repo = 'nvim-lua/diagnostic-nvim'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
hook_source = '''
call deoplete#lsp#enable()
'''

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'let g:deol#prompt_pattern = "% \|%$"'

[[plugins]]
repo = 'tk-shirasaka/ejdict.nvim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_default_executive = 'nvim_lsp'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_source = "lua require'plugin_settings.nvim-treesitter'"

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
hook_source = "lua require'plugin_settings.nvim-treesitter-refactor'"

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
hook_source = "lua require'plugin_settings.nvim-treesitter-textobjects'"

[[plugins]]
repo = 'nvim-treesitter/playground'
hook_source = "lua require'plugin_settings.nvim-treesitter-playground'"

[[plugins]]
repo = 'mfussenegger/nvim-dap'
hook_source = "lua require'plugin_settings.dap'"

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
hook_add = "lua require'plugin_settings.vim-dadbod-ui'"

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'
